# Generated by Django 4.1.6 on 2023-02-13 15:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=130)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
        ),
    ]
