# Generated by Django 4.1.6 on 2023-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(default='img', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.CharField(default='yash', max_length=130),
            preserve_default=False,
        ),
    ]
