# Generated by Django 4.1.6 on 2023-02-14 03:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chapter_image_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheetsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=130)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
        ),
    ]
